### ISSUE TITLE
libcma is not cloned to git/

### ISSUE THREAD

**Issue by barbiani** [embed-me/meta-ebaz4205#2]
I did enable pynq to be added to the bitbake build process and for some reason libcma_1.0.bb does not clone the pynq repository to git/ and the bibtake build fails while reading the LICENSE file.

Tried running 'bitbake -D ebaz4205-image-standard-wic' and it showed no errors during fetch.

Cloning it manually to ~/poky/meta-xilinx/meta-xilinx-pynq/recipes-support/libcma/git/  allows bitbake to finish the image build process.

**Comment by embed-me** [comment]
I am not familiar with the libcma, nor it is part of the meta-ebaz4205 package, therefore I will close the issue for now. If you want to discuss modifications or share your thoughts, please visit my blog [embed-me](https://embed-me.com/blog/).
Thanks.
